
package com.xhsmart.ssmcxf.client_ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "itService", targetNamespace = "http://impl.ws.ssmcxf.xhsmart.com/", wsdlLocation = "http://192.168.10.25:8080/ssmcxf_service/services/xhsmart?wsdl")
public class ItService
    extends Service
{

    private final static URL ITSERVICE_WSDL_LOCATION;
    private final static WebServiceException ITSERVICE_EXCEPTION;
    private final static QName ITSERVICE_QNAME = new QName("http://impl.ws.ssmcxf.xhsmart.com/", "itService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.10.25:8080/ssmcxf_service/services/xhsmart?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ITSERVICE_WSDL_LOCATION = url;
        ITSERVICE_EXCEPTION = e;
    }

    public ItService() {
        super(__getWsdlLocation(), ITSERVICE_QNAME);
    }

    public ItService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ITSERVICE_QNAME, features);
    }

    public ItService(URL wsdlLocation) {
        super(wsdlLocation, ITSERVICE_QNAME);
    }

    public ItService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ITSERVICE_QNAME, features);
    }

    public ItService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ItService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CXFService
     */
    @WebEndpoint(name = "CXFServiceImplPort")
    public CXFService getCXFServiceImplPort() {
        return super.getPort(new QName("http://impl.ws.ssmcxf.xhsmart.com/", "CXFServiceImplPort"), CXFService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CXFService
     */
    @WebEndpoint(name = "CXFServiceImplPort")
    public CXFService getCXFServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.ws.ssmcxf.xhsmart.com/", "CXFServiceImplPort"), CXFService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ITSERVICE_EXCEPTION!= null) {
            throw ITSERVICE_EXCEPTION;
        }
        return ITSERVICE_WSDL_LOCATION;
    }

}
